name: CI/CD for our terraform account stack
on:
  push:
    branches: [ develop ]
    paths:
      - 'infrastructure/account-stack/**'

defaults:
  run:
    working-directory: ./infrastructure/account-stack

jobs:
  account_stack_apply:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform format
        run: terraform fmt
        continue-on-error: true

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        run: terraform apply -auto-approve